# ??????
spring:
  application:
    name: jsoj-backend-question-service
  # ?? dev ??
  profiles:
    active: dev
  # ?? swagger3
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  # session ??
  session:
    store-type: redis
    # 30 ???
  #     timeout: 2592000
  # ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jsoj
    username: root
    password: 123456
  # Redis ??
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 2592000
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
  #    password: 123456
  # ????
  servlet:
    multipart:
      # ????
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8103
  servlet:
    context-path: /api/question
    # cookie 30 ???
    session:
      cookie:
        max-age: 2592000
        path: /api
  # 注册到 nacos 服务
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # ????????????
      logic-delete-value: 1 # ?????????? 1?
      logic-not-delete-value: 0 # ?????????? 0?
# ????
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx
# ??????
knife4j:
  enable: true
codesandbox:
  type: remote