spring:
  application:
    name: jsoj-backend-gateway
  main:
    web-application-type: reactive
  # 注册到 nacos 服务
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: jsoj-backend-user-service
          uri: lb://jsoj-backend-user-service  # 动态路由规则
          predicates:
            - Path=/api/user/**
        - id: jsoj-backend-judge-service
          uri: lb://jsoj-backend-judge-service
          predicates:
            - Path=/api/judge/**
        - id: jsoj-backend-question-service
          uri: lb://jsoj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: jsoj-backend-file-service
          uri: lb://jsoj-backend-file-service
          predicates:
            - Path=/api/file/**
server:
  port: 8101
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2

